# https://taskfile.dev

version: "3"

tasks:
  lint:
    desc: Run base linters
    cmds:
      - golangci-lint run

  test:
    desc: Run tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  fmt:
    desc: Run gofumpt
    cmds:
      - gofumpt -w .
