#!/bin/bash

echo "=== Testing Ctrl+A SelectAll Debug ==="
echo "1. Testing editor SelectAll (should work)"
echo "2. Testing chat SelectAll with manual focus" 
echo "3. Looking for debug output in console"
echo ""
echo "Run: ./crush-debug -d"
echo "Test steps:"
echo "  - Type something in editor"
echo "  - Press Ctrl+A (should select editor text only)" 
echo "  - Press Tab (switch focus to chat)"
echo "  - Press Ctrl+A (should select chat messages)"
echo ""
echo "Expected behavior:"
echo "  - Editor Ctrl+A: selects only input field text"
echo "  - Chat Ctrl+A: selects only chat messages, NOT sidebar"