package orchestra

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/charmbracelet/crush/internal/spec"
)

// BlueprintGenerator generates blueprints from specs.
type BlueprintGenerator struct {
	outputDir string
	templates *template.Template
}

// NewBlueprintGenerator creates a new blueprint generator.
func NewBlueprintGenerator(outputDir string) *BlueprintGenerator {
	return &BlueprintGenerator{
		outputDir: outputDir,
		templates: parseBlueprintTemplates(),
	}
}

// Generate generates all blueprints for a spec.
func (g *BlueprintGenerator) Generate(s spec.Spec) error {
	projectDir := filepath.Join(g.outputDir, s.ID)
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return fmt.Errorf("failed to create blueprint directory: %w", err)
	}

	// Generate README
	if err := g.generateREADME(projectDir, s); err != nil {
		return err
	}

	// Generate architecture document
	if err := g.generateArchitecture(projectDir, s); err != nil {
		return err
	}

	// Generate domain model
	if err := g.generateDomainModel(projectDir, s); err != nil {
		return err
	}

	// Generate API contracts
	if err := g.generateAPIContracts(projectDir, s); err != nil {
		return err
	}

	// Generate user stories
	if err := g.generateUserStories(projectDir, s); err != nil {
		return err
	}

	return nil
}

func (g *BlueprintGenerator) generateREADME(dir string, s spec.Spec) error {
	content := fmt.Sprintf(`# %s

Generated from: specs/%s.yaml v%s
Generated at: %s

## Overview

%s

## Goals

`, s.Name, s.ID, s.Version, time.Now().Format(time.RFC3339), s.Description)

	for _, goal := range s.Goals {
		content += fmt.Sprintf("- %s\n", goal)
	}

	if len(s.NonGoals) > 0 {
		content += "\n## Non-Goals\n\n"
		for _, ng := range s.NonGoals {
			content += fmt.Sprintf("- %s\n", ng)
		}
	}

	content += fmt.Sprintf(`

## Quick Links

- [Architecture](architecture.md) - System architecture overview
- [Domain Model](domain-model.md) - Entity relationships
- [API Contracts](api-contracts.md) - API endpoint contracts
- [User Stories](user-stories.md) - User stories from requirements

## Status

- **Status**: %s
- **Owner**: %s
- **Version**: %s

---
*This blueprint was generated by crush. Update the spec to regenerate.*
`, s.Status, s.Owner, s.Version)

	return os.WriteFile(filepath.Join(dir, "README.md"), []byte(content), 0o644)
}

func (g *BlueprintGenerator) generateArchitecture(dir string, s spec.Spec) error {
	content := fmt.Sprintf(`# %s - Architecture

Generated from: specs/%s.yaml v%s
Generated at: %s

## System Context

`, s.Name, s.ID, s.Version, time.Now().Format(time.RFC3339))

	// Generate mermaid diagram
	content += "```mermaid\ngraph TB\n"

	// Add client nodes
	content += "    Client[Web Client]\n"
	content += "    Mobile[Mobile App]\n"
	content += "    API[API Server]\n"
	content += "    DB[(Database)]\n"

	// Add connections
	content += "    Client --> API\n"
	content += "    Mobile --> API\n"
	content += "    API --> DB\n"

	// Add dependencies
	for _, dep := range s.Dependencies.External {
		name := strings.Split(dep, " ")[0]
		content += fmt.Sprintf("    %s[%s]\n", name, name)
		content += fmt.Sprintf("    API --> %s\n", name)
	}

	content += "```\n\n"

	// Add components section
	content += "## Components\n\n"

	for _, entity := range s.Entities {
		content += fmt.Sprintf("### %s\n", entity.Name)
		content += fmt.Sprintf("%s\n\n", entity.Description)
	}

	// Add constraints
	if len(s.Constraints.Technical) > 0 {
		content += "## Technical Constraints\n\n"
		for _, c := range s.Constraints.Technical {
			content += fmt.Sprintf("- %s\n", c)
		}
		content += "\n"
	}

	if len(s.Constraints.Business) > 0 {
		content += "## Business Constraints\n\n"
		for _, c := range s.Constraints.Business {
			content += fmt.Sprintf("- %s\n", c)
		}
		content += "\n"
	}

	content += fmt.Sprintf(`---
*This blueprint was generated by crush. Update the spec to regenerate.*
`)

	return os.WriteFile(filepath.Join(dir, "architecture.md"), []byte(content), 0o644)
}

func (g *BlueprintGenerator) generateDomainModel(dir string, s spec.Spec) error {
	content := fmt.Sprintf(`# %s - Domain Model

Generated from: specs/%s.yaml v%s
Generated at: %s

## Entity Relationships

`, s.Name, s.ID, s.Version, time.Now().Format(time.RFC3339))

	// Generate mermaid ER diagram
	content += "```mermaid\nerDiagram\n"

	for _, entity := range s.Entities {
		content += fmt.Sprintf("    %s {\n", entity.Name)
		for _, field := range entity.Fields {
			typeStr := field.Type
			content += fmt.Sprintf("        %s %s\n", typeStr, field.Name)
		}
		content += "    }\n"
	}

	// Add relationships
	for _, entity := range s.Entities {
		for _, field := range entity.Fields {
			if field.References != "" {
				parts := strings.Split(field.References, ".")
				if len(parts) >= 2 {
					refEntity := parts[0]
					content += fmt.Sprintf("    %s ||--o{ %s : has\n", refEntity, entity.Name)
				}
			}
		}
	}

	content += "```\n\n"

	// Add entity details
	content += "## Entity Details\n\n"

	for _, entity := range s.Entities {
		content += fmt.Sprintf("### %s\n\n%s\n\n", entity.Name, entity.Description)
		content += "| Field | Type | Description |\n"
		content += "|-------|------|-------------|\n"
		for _, field := range entity.Fields {
			content += fmt.Sprintf("| %s | %s | %s |\n", field.Name, field.Type, field.Description)
		}
		content += "\n"
	}

	content += fmt.Sprintf(`---
*This blueprint was generated by crush. Update the spec to regenerate.*
`)

	return os.WriteFile(filepath.Join(dir, "domain-model.md"), []byte(content), 0o644)
}

func (g *BlueprintGenerator) generateAPIContracts(dir string, s spec.Spec) error {
	content := fmt.Sprintf(`# %s - API Contracts

Generated from: specs/%s.yaml v%s
Generated at: %s

## Endpoints

`, s.Name, s.ID, s.Version, time.Now().Format(time.RFC3339))

	for _, endpoint := range s.APIEndpoints {
		content += fmt.Sprintf("### %s %s\n\n", endpoint.Method, endpoint.Path)
		content += fmt.Sprintf("%s\n\n", endpoint.Description)
		content += fmt.Sprintf("Requirement: %s\n\n", endpoint.Requirement)

		if len(endpoint.Request) > 0 {
			content += "**Request**\n\n"
			content += "| Field | Type |\n"
			content += "|-------|------|\n"
			for name, typ := range endpoint.Request {
				content += fmt.Sprintf("| %s | %s |\n", name, typ)
			}
			content += "\n"
		}

		if len(endpoint.Response) > 0 {
			content += "**Response**\n\n"
			content += "| Field | Type |\n"
			content += "|-------|------|\n"
			for name, typ := range endpoint.Response {
				content += fmt.Sprintf("| %s | %s |\n", name, typ)
			}
			content += "\n"
		}

		if len(endpoint.Errors) > 0 {
			content += "**Errors**\n\n"
			content += "| Code | Message |\n"
			content += "|------|--------|\n"
			for _, err := range endpoint.Errors {
				content += fmt.Sprintf("| %s | %s |\n", err.Code, err.Message)
			}
			content += "\n"
		}

		content += "---\n\n"
	}

	content += fmt.Sprintf(`---
*This blueprint was generated by crush. Update the spec to regenerate.*
`)

	return os.WriteFile(filepath.Join(dir, "api-contracts.md"), []byte(content), 0o644)
}

func (g *BlueprintGenerator) generateUserStories(dir string, s spec.Spec) error {
	content := fmt.Sprintf(`# %s - User Stories

Generated from: specs/%s.yaml v%s
Generated at: %s

## Functional Requirements

`, s.Name, s.ID, s.Version, time.Now().Format(time.RFC3339))

	for _, req := range s.Requirements.Functional {
		content += fmt.Sprintf("### %s: %s\n\n", req.ID, req.Description)
		content += fmt.Sprintf("Priority: %s\n\n", req.Priority)

		content += "**Acceptance Criteria**\n\n"
		for i, ac := range req.AcceptanceCriteria {
			content += fmt.Sprintf("%d. %s\n", i+1, ac)
		}
		content += "\n---\n\n"
	}

	if len(s.Requirements.NonFunctional) > 0 {
		content += "## Non-Functional Requirements\n\n"

		for _, req := range s.Requirements.NonFunctional {
			content += fmt.Sprintf("### %s: %s\n\n", req.ID, req.Description)
			content += fmt.Sprintf("Category: %s\n\n", req.Category)
			content += fmt.Sprintf("%s\n\n", req.Details)
			content += "---\n\n"
		}
	}

	content += fmt.Sprintf(`---
*This blueprint was generated by crush. Update the spec to regenerate.*
`)

	return os.WriteFile(filepath.Join(dir, "user-stories.md"), []byte(content), 0o644)
}

func parseBlueprintTemplates() *template.Template {
	return template.New("blueprints")
}
