package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

var buildTemplate = template.Must(template.New("main").Parse(`// Code generated by xcrush. DO NOT EDIT.
package main

import (
	"log/slog"
	"net/http"
	_ "net/http/pprof"
	"os"

	"github.com/charmbracelet/crush/cmd/crush"
	_ "github.com/joho/godotenv/autoload"

	// Plugin imports
{{range .Plugins}}	_ "{{.}}"
{{end}}
)

func main() {
	if os.Getenv("CRUSH_PROFILE") != "" {
		go func() {
			slog.Info("Serving pprof at localhost:6060")
			if httpErr := http.ListenAndServe("localhost:6060", nil); httpErr != nil {
				slog.Error("Failed to pprof listen", "error", httpErr)
			}
		}()
	}

	crush.Execute()
}
`))

type buildFlags struct {
	plugins   []string
	output    string
	crushPath string
	skipClean bool
	goFlags   string
	ldFlags   string
}

func buildCmd() *cobra.Command {
	flags := &buildFlags{}

	cmd := &cobra.Command{
		Use:   "build",
		Short: "Build Crush with extensions",
		Long: `Build a custom Crush binary with the specified extensions.
Extensions are Go modules that register themselves via init() functions.`,
		Example: `  # Build with a remote extension
  xcrush build --with github.com/example/crush-ext-jira@v1.0.0

  # Build with a local extension
  xcrush build --with ./my-extension

  # Build with multiple extensions
  xcrush build \
    --with github.com/example/crush-ext-jira@v1.0.0 \
    --with github.com/example/crush-ext-datadog@v1.0.0

  # Build with custom output path
  xcrush build --with ./my-extension --output ./crush-custom`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runBuild(flags)
		},
	}

	cmd.Flags().StringArrayVar(&flags.plugins, "with", nil, "Extension module path (can be specified multiple times)")
	cmd.Flags().StringVarP(&flags.output, "output", "o", "./crush", "Output binary path")
	cmd.Flags().StringVar(&flags.crushPath, "crush", "", "Crush module path (defaults to local)")
	cmd.Flags().BoolVar(&flags.skipClean, "skip-clean", false, "Skip cleaning temporary build directory")
	cmd.Flags().StringVar(&flags.goFlags, "go-flags", "", "Additional flags to pass to go build")
	cmd.Flags().StringVar(&flags.ldFlags, "ldflags", "", "Linker flags to pass to go build")

	return cmd
}

func runBuild(flags *buildFlags) error {
	if len(flags.plugins) == 0 {
		fmt.Println("No extensions specified. Building vanilla Crush...")
	}

	// Create temporary build directory.
	tmpDir, err := os.MkdirTemp("", "xcrush-build-*")
	if err != nil {
		return fmt.Errorf("failed to create temp directory: %w", err)
	}
	if !flags.skipClean {
		defer os.RemoveAll(tmpDir)
	} else {
		fmt.Printf("Build directory: %s\n", tmpDir)
	}

	// Get the current module path for Crush.
	crushModule := "github.com/charmbracelet/crush"
	var crushLocalPath string

	if flags.crushPath != "" {
		// Check if it's a local path.
		if strings.HasPrefix(flags.crushPath, "./") || strings.HasPrefix(flags.crushPath, "/") || strings.HasPrefix(flags.crushPath, "../") {
			absPath, err := filepath.Abs(flags.crushPath)
			if err != nil {
				return fmt.Errorf("failed to resolve crush path: %w", err)
			}
			crushLocalPath = absPath
		} else {
			crushModule = flags.crushPath
		}
	}

	// Generate go.mod.
	goModContent := fmt.Sprintf(`module xcrush-build

go 1.25.5

require (
	%s v0.0.0
)
`, crushModule)

	// Add replace directive for local Crush.
	if crushLocalPath != "" {
		goModContent += fmt.Sprintf("\nreplace %s => %s\n", crushModule, crushLocalPath)
	} else if flags.crushPath == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get current directory: %w", err)
		}
		goModContent += fmt.Sprintf("\nreplace %s => %s\n", crushModule, cwd)
	}

	// Add replace directives for local plugins.
	for _, plugin := range flags.plugins {
		if strings.HasPrefix(plugin, "./") || strings.HasPrefix(plugin, "/") {
			absPath, err := filepath.Abs(plugin)
			if err != nil {
				return fmt.Errorf("failed to resolve plugin path %s: %w", plugin, err)
			}
			// Read the plugin's go.mod to get its module path.
			modPath := filepath.Join(absPath, "go.mod")
			modContent, err := os.ReadFile(modPath)
			if err != nil {
				return fmt.Errorf("failed to read plugin go.mod at %s: %w", modPath, err)
			}
			moduleName := extractModuleName(string(modContent))
			if moduleName == "" {
				return fmt.Errorf("could not extract module name from %s", modPath)
			}
			goModContent += fmt.Sprintf("replace %s => %s\n", moduleName, absPath)

			// Propagate replace directives from plugin's go.mod, resolving relative paths.
			for _, replace := range extractReplaceDirectives(string(modContent)) {
				// Skip the crush replace since we already added it.
				if replace.Module == crushModule {
					continue
				}
				targetPath := replace.Path
				if !filepath.IsAbs(targetPath) {
					targetPath = filepath.Join(absPath, targetPath)
					targetPath, _ = filepath.Abs(targetPath)
				}
				goModContent += fmt.Sprintf("replace %s => %s\n", replace.Module, targetPath)
			}
		}
	}

	goModPath := filepath.Join(tmpDir, "go.mod")
	if err := os.WriteFile(goModPath, []byte(goModContent), 0o644); err != nil {
		return fmt.Errorf("failed to write go.mod: %w", err)
	}

	// Normalize plugin paths for imports.
	var pluginImports []string
	for _, plugin := range flags.plugins {
		if strings.HasPrefix(plugin, "./") || strings.HasPrefix(plugin, "/") {
			absPath, err := filepath.Abs(plugin)
			if err != nil {
				return fmt.Errorf("failed to resolve plugin path %s: %w", plugin, err)
			}
			modPath := filepath.Join(absPath, "go.mod")
			modContent, err := os.ReadFile(modPath)
			if err != nil {
				return fmt.Errorf("failed to read plugin go.mod: %w", err)
			}
			moduleName := extractModuleName(string(modContent))
			if moduleName != "" {
				pluginImports = append(pluginImports, moduleName)
			}
		} else {
			// Remote module - strip version for import.
			importPath := plugin
			if idx := strings.Index(plugin, "@"); idx > 0 {
				importPath = plugin[:idx]
			}
			pluginImports = append(pluginImports, importPath)
		}
	}

	// Generate main.go.
	mainPath := filepath.Join(tmpDir, "main.go")
	mainFile, err := os.Create(mainPath)
	if err != nil {
		return fmt.Errorf("failed to create main.go: %w", err)
	}
	defer mainFile.Close()

	if err := buildTemplate.Execute(mainFile, struct {
		Plugins []string
	}{
		Plugins: pluginImports,
	}); err != nil {
		return fmt.Errorf("failed to generate main.go: %w", err)
	}

	// Run go mod tidy.
	fmt.Println("Running go mod tidy...")
	tidyCmd := exec.Command("go", "mod", "tidy")
	tidyCmd.Dir = tmpDir
	tidyCmd.Stdout = os.Stdout
	tidyCmd.Stderr = os.Stderr
	if err := tidyCmd.Run(); err != nil {
		return fmt.Errorf("go mod tidy failed: %w", err)
	}

	// Build the binary.
	fmt.Println("Building...")
	buildArgs := []string{"build"}
	if flags.ldFlags != "" {
		buildArgs = append(buildArgs, "-ldflags", flags.ldFlags)
	}
	if flags.goFlags != "" {
		buildArgs = append(buildArgs, strings.Fields(flags.goFlags)...)
	}

	outputPath, err := filepath.Abs(flags.output)
	if err != nil {
		return fmt.Errorf("failed to resolve output path: %w", err)
	}
	buildArgs = append(buildArgs, "-o", outputPath, ".")

	buildCmd := exec.Command("go", buildArgs...)
	buildCmd.Dir = tmpDir
	buildCmd.Stdout = os.Stdout
	buildCmd.Stderr = os.Stderr
	if err := buildCmd.Run(); err != nil {
		return fmt.Errorf("go build failed: %w", err)
	}

	fmt.Printf("Built successfully: %s\n", outputPath)
	if len(flags.plugins) > 0 {
		fmt.Printf("Included extensions:\n")
		for _, p := range pluginImports {
			fmt.Printf("  - %s\n", p)
		}
	}

	return nil
}

// extractModuleName extracts the module name from go.mod content.
func extractModuleName(content string) string {
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module "))
		}
	}
	return ""
}

// replaceDirective represents a replace directive in go.mod.
type replaceDirective struct {
	Module string
	Path   string
}

// extractReplaceDirectives extracts replace directives from go.mod content.
func extractReplaceDirectives(content string) []replaceDirective {
	var directives []replaceDirective
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "replace ") {
			// Format: replace module => path
			line = strings.TrimPrefix(line, "replace ")
			parts := strings.Split(line, "=>")
			if len(parts) == 2 {
				module := strings.TrimSpace(parts[0])
				path := strings.TrimSpace(parts[1])
				directives = append(directives, replaceDirective{Module: module, Path: path})
			}
		}
	}
	return directives
}
