// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package db

import (
	"context"
)

const addCheckpointFile = `-- name: AddCheckpointFile :exec
INSERT INTO checkpoint_files (checkpoint_id, file_id)
VALUES (?, ?)
`

type AddCheckpointFileParams struct {
	CheckpointID string `json:"checkpoint_id"`
	FileID       string `json:"file_id"`
}

func (q *Queries) AddCheckpointFile(ctx context.Context, arg AddCheckpointFileParams) error {
	_, err := q.exec(ctx, q.addCheckpointFileStmt, addCheckpointFile, arg.CheckpointID, arg.FileID)
	return err
}

const countCheckpointFiles = `-- name: CountCheckpointFiles :one
SELECT COUNT(*) FROM checkpoint_files WHERE checkpoint_id = ?
`

func (q *Queries) CountCheckpointFiles(ctx context.Context, checkpointID string) (int64, error) {
	row := q.queryRow(ctx, q.countCheckpointFilesStmt, countCheckpointFiles, checkpointID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckpoint = `-- name: CreateCheckpoint :one
INSERT INTO checkpoints (id, session_id, message_id, created_at)
VALUES (?, ?, ?, strftime('%s', 'now'))
RETURNING id, session_id, message_id, created_at
`

type CreateCheckpointParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	MessageID string `json:"message_id"`
}

func (q *Queries) CreateCheckpoint(ctx context.Context, arg CreateCheckpointParams) (Checkpoint, error) {
	row := q.queryRow(ctx, q.createCheckpointStmt, createCheckpoint, arg.ID, arg.SessionID, arg.MessageID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCheckpoint = `-- name: DeleteCheckpoint :exec
DELETE FROM checkpoints WHERE id = ?
`

func (q *Queries) DeleteCheckpoint(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteCheckpointStmt, deleteCheckpoint, id)
	return err
}

const deleteSessionCheckpoints = `-- name: DeleteSessionCheckpoints :exec
DELETE FROM checkpoints WHERE session_id = ?
`

func (q *Queries) DeleteSessionCheckpoints(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionCheckpointsStmt, deleteSessionCheckpoints, sessionID)
	return err
}

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT id, session_id, message_id, created_at FROM checkpoints WHERE id = ? LIMIT 1
`

func (q *Queries) GetCheckpoint(ctx context.Context, id string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getCheckpointStmt, getCheckpoint, id)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getCheckpointByMessageID = `-- name: GetCheckpointByMessageID :one
SELECT id, session_id, message_id, created_at FROM checkpoints
WHERE message_id = ?
LIMIT 1
`

func (q *Queries) GetCheckpointByMessageID(ctx context.Context, messageID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getCheckpointByMessageIDStmt, getCheckpointByMessageID, messageID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestSessionCheckpoint = `-- name: GetLatestSessionCheckpoint :one
SELECT id, session_id, message_id, created_at FROM checkpoints
WHERE session_id = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSessionCheckpoint(ctx context.Context, sessionID string) (Checkpoint, error) {
	row := q.queryRow(ctx, q.getLatestSessionCheckpointStmt, getLatestSessionCheckpoint, sessionID)
	var i Checkpoint
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const listCheckpointFiles = `-- name: ListCheckpointFiles :many
SELECT f.id, f.session_id, f.path, f.content, f.version, f.created_at, f.updated_at
FROM files f
INNER JOIN checkpoint_files cf ON f.id = cf.file_id
WHERE cf.checkpoint_id = ?
ORDER BY f.path
`

func (q *Queries) ListCheckpointFiles(ctx context.Context, checkpointID string) ([]File, error) {
	rows, err := q.query(ctx, q.listCheckpointFilesStmt, listCheckpointFiles, checkpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Path,
			&i.Content,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionCheckpoints = `-- name: ListSessionCheckpoints :many
SELECT id, session_id, message_id, created_at FROM checkpoints
WHERE session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionCheckpoints(ctx context.Context, sessionID string) ([]Checkpoint, error) {
	rows, err := q.query(ctx, q.listSessionCheckpointsStmt, listSessionCheckpoints, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Checkpoint{}
	for rows.Next() {
		var i Checkpoint
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
