// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Message struct {
	ID                      string          `json:"id"`
	SessionID               string          `json:"session_id"`
	Role                    string          `json:"role"`
	Parts                   string          `json:"parts"`
	Model                   sql.NullString  `json:"model"`
	CreatedAt               int64           `json:"created_at"`
	UpdatedAt               int64           `json:"updated_at"`
	FinishedAt              sql.NullInt64   `json:"finished_at"`
	Provider                sql.NullString  `json:"provider"`
	IsSummaryMessage        int64           `json:"is_summary_message"`
	PrismModelID            sql.NullString  `json:"prism_model_id"`
	PrismModelName          sql.NullString  `json:"prism_model_name"`
	PrismHypercreditSavings sql.NullFloat64 `json:"prism_hypercredit_savings"`
	PrismDollarSavings      sql.NullFloat64 `json:"prism_dollar_savings"`
}

type NotebookEntry struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	TurnNumber       int64          `json:"turn_number"`
	EventNumber      int64          `json:"event_number"`
	EventType        string         `json:"event_type"`
	Title            string         `json:"title"`
	EntryText        string         `json:"entry_text"`
	EntryTextFull    sql.NullString `json:"entry_text_full"`
	TokenCount       int64          `json:"token_count"`
	CompressionLevel int64          `json:"compression_level"`
	CreatedAt        int64          `json:"created_at"`
	Succeeded        int64          `json:"succeeded"`
	ErrorHeadline    string         `json:"error_headline"`
}

type NotebookTag struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

type ReadFile struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	ReadAt    int64  `json:"read_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
	Todos            sql.NullString `json:"todos"`
}
