// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notebook.sql

package db

import (
	"context"
	"database/sql"
)

const createNotebookEntry = `-- name: CreateNotebookEntry :one
INSERT INTO notebook_entries (
    id,
    session_id,
    turn_number,
    event_number,
    event_type,
    title,
    entry_text,
    entry_text_full,
    token_count,
    compression_level,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
`

type CreateNotebookEntryParams struct {
	ID               string         `json:"id"`
	SessionID        string         `json:"session_id"`
	TurnNumber       int64          `json:"turn_number"`
	EventNumber      int64          `json:"event_number"`
	EventType        string         `json:"event_type"`
	Title            string         `json:"title"`
	EntryText        string         `json:"entry_text"`
	EntryTextFull    sql.NullString `json:"entry_text_full"`
	TokenCount       int64          `json:"token_count"`
	CompressionLevel int64          `json:"compression_level"`
	CreatedAt        int64          `json:"created_at"`
}

func (q *Queries) CreateNotebookEntry(ctx context.Context, arg CreateNotebookEntryParams) (NotebookEntry, error) {
	row := q.queryRow(ctx, q.createNotebookEntryStmt, createNotebookEntry,
		arg.ID,
		arg.SessionID,
		arg.TurnNumber,
		arg.EventNumber,
		arg.EventType,
		arg.Title,
		arg.EntryText,
		arg.EntryTextFull,
		arg.TokenCount,
		arg.CompressionLevel,
		arg.CreatedAt,
	)
	var i NotebookEntry
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TurnNumber,
		&i.EventNumber,
		&i.EventType,
		&i.Title,
		&i.EntryText,
		&i.TokenCount,
		&i.CompressionLevel,
		&i.CreatedAt,
		&i.EntryTextFull,
	)
	return i, err
}

const createNotebookTag = `-- name: CreateNotebookTag :exec
INSERT OR IGNORE INTO notebook_tags (entry_id, tag)
VALUES (?, ?)
`

type CreateNotebookTagParams struct {
	EntryID string `json:"entry_id"`
	Tag     string `json:"tag"`
}

func (q *Queries) CreateNotebookTag(ctx context.Context, arg CreateNotebookTagParams) error {
	_, err := q.exec(ctx, q.createNotebookTagStmt, createNotebookTag, arg.EntryID, arg.Tag)
	return err
}

const deleteNotebookEntriesBySession = `-- name: DeleteNotebookEntriesBySession :exec
DELETE FROM notebook_entries
WHERE session_id = ?
`

func (q *Queries) DeleteNotebookEntriesBySession(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteNotebookEntriesBySessionStmt, deleteNotebookEntriesBySession, sessionID)
	return err
}

const getNotebookEntries = `-- name: GetNotebookEntries :many
SELECT id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
FROM notebook_entries
WHERE session_id = ?
ORDER BY turn_number ASC, event_number ASC
`

func (q *Queries) GetNotebookEntries(ctx context.Context, sessionID string) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.getNotebookEntriesStmt, getNotebookEntries, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotebookEntriesByEventType = `-- name: GetNotebookEntriesByEventType :many
SELECT id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
FROM notebook_entries
WHERE session_id = ? AND event_type = ?
ORDER BY turn_number ASC, event_number ASC
`

type GetNotebookEntriesByEventTypeParams struct {
	SessionID string `json:"session_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) GetNotebookEntriesByEventType(ctx context.Context, arg GetNotebookEntriesByEventTypeParams) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.getNotebookEntriesByEventTypeStmt, getNotebookEntriesByEventType, arg.SessionID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotebookEntriesByTurn = `-- name: GetNotebookEntriesByTurn :many
SELECT id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
FROM notebook_entries
WHERE session_id = ? AND turn_number = ?
ORDER BY event_number ASC
`

type GetNotebookEntriesByTurnParams struct {
	SessionID  string `json:"session_id"`
	TurnNumber int64  `json:"turn_number"`
}

func (q *Queries) GetNotebookEntriesByTurn(ctx context.Context, arg GetNotebookEntriesByTurnParams) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.getNotebookEntriesByTurnStmt, getNotebookEntriesByTurn, arg.SessionID, arg.TurnNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotebookEntryCount = `-- name: GetNotebookEntryCount :one
SELECT COUNT(*) AS entry_count
FROM notebook_entries
WHERE session_id = ?
`

func (q *Queries) GetNotebookEntryCount(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.getNotebookEntryCountStmt, getNotebookEntryCount, sessionID)
	var entry_count int64
	err := row.Scan(&entry_count)
	return entry_count, err
}

const getNotebookTagsByEntry = `-- name: GetNotebookTagsByEntry :many
SELECT tag
FROM notebook_tags
WHERE entry_id = ?
`

func (q *Queries) GetNotebookTagsByEntry(ctx context.Context, entryID string) ([]string, error) {
	rows, err := q.query(ctx, q.getNotebookTagsByEntryStmt, getNotebookTagsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotebookTokenCount = `-- name: GetNotebookTokenCount :one
SELECT CAST(COALESCE(SUM(token_count), 0) AS INTEGER) as total_tokens
FROM notebook_entries
WHERE session_id = ?
`

func (q *Queries) GetNotebookTokenCount(ctx context.Context, sessionID string) (int64, error) {
	row := q.queryRow(ctx, q.getNotebookTokenCountStmt, getNotebookTokenCount, sessionID)
	var total_tokens int64
	err := row.Scan(&total_tokens)
	return total_tokens, err
}

const getOldestNotebookEntries = `-- name: GetOldestNotebookEntries :many
SELECT id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
FROM notebook_entries
WHERE session_id = ? AND compression_level = ?
ORDER BY turn_number ASC, event_number ASC
LIMIT ?
`

type GetOldestNotebookEntriesParams struct {
	SessionID        string `json:"session_id"`
	CompressionLevel int64  `json:"compression_level"`
	Limit            int64  `json:"limit"`
}

func (q *Queries) GetOldestNotebookEntries(ctx context.Context, arg GetOldestNotebookEntriesParams) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.getOldestNotebookEntriesStmt, getOldestNotebookEntries, arg.SessionID, arg.CompressionLevel, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotebookByTag = `-- name: SearchNotebookByTag :many
SELECT DISTINCT e.id, e.session_id, e.turn_number, e.event_number, e.event_type, e.title, e.entry_text, e.token_count, e.compression_level, e.created_at, e.entry_text_full
FROM notebook_entries e
JOIN notebook_tags t ON t.entry_id = e.id
WHERE e.session_id = ? AND t.tag = ?
ORDER BY e.turn_number ASC, e.event_number ASC
`

type SearchNotebookByTagParams struct {
	SessionID string `json:"session_id"`
	Tag       string `json:"tag"`
}

func (q *Queries) SearchNotebookByTag(ctx context.Context, arg SearchNotebookByTagParams) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.searchNotebookByTagStmt, searchNotebookByTag, arg.SessionID, arg.Tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotebookByText = `-- name: SearchNotebookByText :many
SELECT id, session_id, turn_number, event_number, event_type, title, entry_text, token_count, compression_level, created_at, entry_text_full
FROM notebook_entries
WHERE session_id = ? AND entry_text LIKE ?2
ORDER BY turn_number ASC, event_number ASC
`

type SearchNotebookByTextParams struct {
	SessionID  string `json:"session_id"`
	SearchTerm string `json:"search_term"`
}

func (q *Queries) SearchNotebookByText(ctx context.Context, arg SearchNotebookByTextParams) ([]NotebookEntry, error) {
	rows, err := q.query(ctx, q.searchNotebookByTextStmt, searchNotebookByText, arg.SessionID, arg.SearchTerm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotebookEntry{}
	for rows.Next() {
		var i NotebookEntry
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TurnNumber,
			&i.EventNumber,
			&i.EventType,
			&i.Title,
			&i.EntryText,
			&i.TokenCount,
			&i.CompressionLevel,
			&i.CreatedAt,
			&i.EntryTextFull,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotebookCompression = `-- name: UpdateNotebookCompression :exec
UPDATE notebook_entries
SET
    entry_text = ?,
    token_count = ?,
    compression_level = ?
WHERE id = ?
`

type UpdateNotebookCompressionParams struct {
	EntryText        string `json:"entry_text"`
	TokenCount       int64  `json:"token_count"`
	CompressionLevel int64  `json:"compression_level"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateNotebookCompression(ctx context.Context, arg UpdateNotebookCompressionParams) error {
	_, err := q.exec(ctx, q.updateNotebookCompressionStmt, updateNotebookCompression,
		arg.EntryText,
		arg.TokenCount,
		arg.CompressionLevel,
		arg.ID,
	)
	return err
}
