// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read_files.sql

package db

import (
	"context"
)

const getFileRead = `-- name: GetFileRead :one
SELECT session_id, path, read_at, last_read_at, last_read_mtime_ns, last_read_size, last_included_at, last_included_mtime_ns, last_included_size, last_included_epoch FROM read_files
WHERE session_id = ? AND path = ? LIMIT 1
`

type GetFileReadParams struct {
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
}

func (q *Queries) GetFileRead(ctx context.Context, arg GetFileReadParams) (ReadFile, error) {
	row := q.queryRow(ctx, q.getFileReadStmt, getFileRead, arg.SessionID, arg.Path)
	var i ReadFile
	err := row.Scan(
		&i.SessionID,
		&i.Path,
		&i.ReadAt,
		&i.LastReadAt,
		&i.LastReadMtimeNs,
		&i.LastReadSize,
		&i.LastIncludedAt,
		&i.LastIncludedMtimeNs,
		&i.LastIncludedSize,
		&i.LastIncludedEpoch,
	)
	return i, err
}

const listSessionReadFiles = `-- name: ListSessionReadFiles :many
SELECT session_id, path, read_at, last_read_at, last_read_mtime_ns, last_read_size, last_included_at, last_included_mtime_ns, last_included_size, last_included_epoch FROM read_files
WHERE session_id = ?
  AND (last_read_at > 0 OR last_included_at > 0)
ORDER BY MAX(last_read_at, last_included_at) DESC
`

func (q *Queries) ListSessionReadFiles(ctx context.Context, sessionID string) ([]ReadFile, error) {
	rows, err := q.query(ctx, q.listSessionReadFilesStmt, listSessionReadFiles, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadFile{}
	for rows.Next() {
		var i ReadFile
		if err := rows.Scan(
			&i.SessionID,
			&i.Path,
			&i.ReadAt,
			&i.LastReadAt,
			&i.LastReadMtimeNs,
			&i.LastReadSize,
			&i.LastIncludedAt,
			&i.LastIncludedMtimeNs,
			&i.LastIncludedSize,
			&i.LastIncludedEpoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFileIncludedInContext = `-- name: RecordFileIncludedInContext :exec
INSERT INTO read_files (
    session_id,
    path,
    read_at,
    last_included_at,
    last_included_mtime_ns,
    last_included_size,
    last_included_epoch
) VALUES (
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    ?,
    ?,
    ?
) ON CONFLICT(path, session_id) DO UPDATE SET
    read_at = excluded.read_at,
    last_included_at = excluded.last_included_at,
    last_included_mtime_ns = excluded.last_included_mtime_ns,
    last_included_size = excluded.last_included_size,
    last_included_epoch = excluded.last_included_epoch
`

type RecordFileIncludedInContextParams struct {
	SessionID           string `json:"session_id"`
	Path                string `json:"path"`
	LastIncludedMtimeNs int64  `json:"last_included_mtime_ns"`
	LastIncludedSize    int64  `json:"last_included_size"`
	LastIncludedEpoch   int64  `json:"last_included_epoch"`
}

func (q *Queries) RecordFileIncludedInContext(ctx context.Context, arg RecordFileIncludedInContextParams) error {
	_, err := q.exec(ctx, q.recordFileIncludedInContextStmt, recordFileIncludedInContext,
		arg.SessionID,
		arg.Path,
		arg.LastIncludedMtimeNs,
		arg.LastIncludedSize,
		arg.LastIncludedEpoch,
	)
	return err
}

const recordFileRead = `-- name: RecordFileRead :exec
INSERT INTO read_files (
    session_id,
    path,
    read_at,
    last_read_at,
    last_read_mtime_ns,
    last_read_size
) VALUES (
    ?,
    ?,
    strftime('%s', 'now'),
    strftime('%s', 'now'),
    ?,
    ?
) ON CONFLICT(path, session_id) DO UPDATE SET
    read_at = excluded.read_at,
    last_read_at = excluded.last_read_at,
    last_read_mtime_ns = excluded.last_read_mtime_ns,
    last_read_size = excluded.last_read_size
`

type RecordFileReadParams struct {
	SessionID       string `json:"session_id"`
	Path            string `json:"path"`
	LastReadMtimeNs int64  `json:"last_read_mtime_ns"`
	LastReadSize    int64  `json:"last_read_size"`
}

func (q *Queries) RecordFileRead(ctx context.Context, arg RecordFileReadParams) error {
	_, err := q.exec(ctx, q.recordFileReadStmt, recordFileRead,
		arg.SessionID,
		arg.Path,
		arg.LastReadMtimeNs,
		arg.LastReadSize,
	)
	return err
}
