// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills_toggle.sql

package db

import (
	"context"
)

const deleteSkillsDisabled = `-- name: DeleteSkillsDisabled :exec
DELETE FROM skills_disabled_servers WHERE name = ?
`

func (q *Queries) DeleteSkillsDisabled(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteSkillsDisabledStmt, deleteSkillsDisabled, name)
	return err
}

const deleteSkillsEnabled = `-- name: DeleteSkillsEnabled :exec
DELETE FROM skills_enabled_servers WHERE name = ?
`

func (q *Queries) DeleteSkillsEnabled(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteSkillsEnabledStmt, deleteSkillsEnabled, name)
	return err
}

const insertSkillsDisabled = `-- name: InsertSkillsDisabled :exec
INSERT OR IGNORE INTO skills_disabled_servers (name) VALUES (?)
`

func (q *Queries) InsertSkillsDisabled(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.insertSkillsDisabledStmt, insertSkillsDisabled, name)
	return err
}

const insertSkillsEnabled = `-- name: InsertSkillsEnabled :exec
INSERT OR IGNORE INTO skills_enabled_servers (name) VALUES (?)
`

func (q *Queries) InsertSkillsEnabled(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.insertSkillsEnabledStmt, insertSkillsEnabled, name)
	return err
}

const listSkillsDisabled = `-- name: ListSkillsDisabled :many
SELECT name FROM skills_disabled_servers ORDER BY name
`

func (q *Queries) ListSkillsDisabled(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listSkillsDisabledStmt, listSkillsDisabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsEnabled = `-- name: ListSkillsEnabled :many
SELECT name FROM skills_enabled_servers ORDER BY name
`

func (q *Queries) ListSkillsEnabled(ctx context.Context) ([]string, error) {
	rows, err := q.query(ctx, q.listSkillsEnabledStmt, listSkillsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
